### ISSUE TITLE
How to get most recent data?

### ISSUE THREAD

**Issue by zahidhussaina2l** [soheilrahsaz/cryptoNewsDataset#1]
Hey, not an issue but do you have the most recent data for new or update this because cryptopanic only gives most recent 200 news but I need to have complete data for my research.

Is there any possibility for that?

**Comment by soheilrahsaz** [comment]
Hello
I will update the news from the last two months by tomorrow.

**Comment by zahidhussaina2l** [comment]
That would be awesome, can you please tell me how do you do that? if I want to get the data myself?

**Comment by soheilrahsaz** [comment]
I use their public API, which gives me only 200 news items. However, the API accepts filters (rising, bullish, bearish, important, hot, saved, lol) and also currency. For each currency (about 430 of them), I make 8 API calls (one for each filter and one without any filter). In total, I retrieve 1,600 news items for each trending currency. After removing duplicates, I end up with about 1,200 unique news items from the past 4-6 months.
I started this process years ago, so I have almost all the important news from the past 5 years.


P.S.: I'm almost done fetching the news from the past 2 months, and I'll update the repository shortly.
